version: '3.8'

services:
  web:
    image: capezero_assignment
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8080
      "
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    environment:
      - DEBUG=1
    networks:
      - django-network

networks:
  django-network: