# Generated by Django 4.2.6 on 2024-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record is created!')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was modified!')),
                ('name', models.CharField(max_length=200)),
                ('fmv', models.FloatField(default=0, help_text='Fair market value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When this record is created!')),
                ('updated', models.DateTimeField(auto_now=True, help_text='When this record was modified!')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tax_credit_transfer_rate', models.FloatField()),
                ('projects', models.ManyToManyField(related_name='deals', to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
